name = "CelluloseBuilder"
uuid = "f5258e19-0f4f-4595-8a18-bcc895194118"
authors = ["cgtbatista <c203748@dac.unicamp.br> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LinearAlgebra = "1.10"
Measurements = "2.12.0"
PDBTools = "0.13.14, 1.8.1, 2.1.3"
Printf = "1.11.0"
StaticArrays = "1.6"
Test = "1.9"
TestItemRunner = "1"
TestItems = "1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"


[targets]
test = ["Test", "TestItems", "TestItemRunner"]
